spring:
  profiles.active: local
---
spring:
  profiles: default
---
spring:
  profiles: local
  database:
    url: jdbc:mysql://localhost:3306/modelmate
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: hello12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/
server:
  port: 8080
---
spring:
  profiles: ec2
  database:
    url: jdbc:mysql://localhost:3306/modelmate
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: Password123#@!
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/
server:
  port: 8080

---
spring:
  jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl